# Generated by Django 5.0.7 on 2024-08-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
            },
        ),
        migrations.AlterField(
            model_name="blog",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Просмотры"
            ),
        ),
    ]
