# Generated by Django 5.0.7 on 2024-08-02 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_version",
                    models.FloatField(
                        help_text="Введите номер версии продукта",
                        verbose_name="Номер версии",
                    ),
                ),
                (
                    "name_version",
                    models.CharField(
                        blank=True,
                        help_text="Введите название версии продукта",
                        max_length=250,
                        null=True,
                        verbose_name="Название версии",
                    ),
                ),
                (
                    "current_version_flag",
                    models.BooleanField(
                        help_text="Установите флаг текущей версии",
                        verbose_name="Текущая версия",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Выберите продукт",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="catalog.product",
                        verbose_name="Наименование продукта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия продукта",
                "verbose_name_plural": "Версии продуктов",
                "ordering": ("number_version",),
            },
        ),
    ]
