# Generated by Django 5.0.7 on 2024-08-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="введите цену на единицу товара",
                null=True,
                verbose_name="Цена",
            ),
        ),
    ]
